### ISSUE TITLE
Unauthorized when dipatch refresh token

### ISSUE THREAD

**Issue by shmdesign** [iliyaZelenko/laravel5.7-vue-cli3-boilerplate#1]
Hi there,

Thank you for this tremending boilerplate. I am trying to implement this and I think the last thing where I am failing is the refresh token from vuex.

I don't really get how to implement this as I keep receiving an Unauthorized response from laravel.

Could anyone help?

**Comment by 777genius** [comment]
Hi, try to help. I wrote all the authorization myself, including the refresh token. In my opinion, when I checked everything worked for me and judging by the stars for other people, it also works.

The refresh token system is arranged so that if the token expires soon ([the variable period is set](https://github.com/iliyaZelenko/laravel5.7-vue-cli3-boilerplate/blob/master/frontend/src/store/modules/auth/index.js#L14)) then a request is made to update the token (see [refresh action dispatching](https://github.com/iliyaZelenko/laravel5.7-vue-cli3-boilerplate/blob/master/frontend/src/store/modules/auth/index.js#L172) and [post request from refresh action](https://github.com/iliyaZelenko/laravel5.7-vue-cli3-boilerplate/blob/master/frontend/src/store/modules/auth/index.js#L111)).

Does this error always occur when script need to refresh the token? Is the authorization header transmitted? (Authorization bearer). Does the authentication token work for routes requiring authentication?

As a temporary solution, you can increase the life of the token on [server](https://github.com/iliyaZelenko/laravel5.7-vue-cli3-boilerplate/blob/master/config/jwt.php#L103) and  [this variable on client](https://github.com/iliyaZelenko/laravel5.7-vue-cli3-boilerplate/blob/master/frontend/src/store/modules/auth/index.js#L14).

I am wondering if this error is in my code. I wrote this code for a long time and I don’t remember if I completed everything there. 

I have a version of the same project, but there I added and changed a lot, everything seems to work, but I didn’t manage to finish everything. I also have a project with fully tested authorization on Laravel and Vue, but Nuxt.js is used there, maybe it won't suit you. 

I also have a project on a github that I am working on at the moment, there is a [very similar authorization](https://github.com/iliyaZelenko/blog-laravel/blob/master/frontend/src/store/modules/auth/index.ts) that has been fully tested and works fine, but again the front also uses Nuxt.js and another TypeScript, on the same technology (authorization is not on GraphQl). You can take the modified code from there. 




I will be happy to help.

**Comment by shmdesign** [comment]
Hi, Thanks for the swift answer. this is not really an issue per se. I am happy to close this and carry on via email if easier. 

The thing I am trying to understand is not to log people off if the token has expired. I am trying to implement this auth/mechanism for something that might play on both mobile and web. It would be quite horrible for mobile users to log back in every hour. But I believe web people should be logged out every hour.

I am not sure this is very clear but I am happy to discuss more.

Again,

Thanks (you deserve your stars, the code is great!)

**Comment by 777genius** [comment]
But I have implemented this system about which you write: if the access token expires, then the token is refreshed and so on until the refresh token [expires](https://github.com/iliyaZelenko/laravel5.7-vue-cli3-boilerplate/blob/master/config/jwt.php#L122). 

If you need mobile and desktop users to have a different duration of the session as you wrote, then you need to somehow change the TTL of the refresh token depending on the device. The frontend sends the user device and the server creates a token with the desired TTL. I'm sure the `tymon/jwt-auth` library  (used in this project) can do that.

I wonder why you think desktop users should have an hour session? I think it is also not convenient to constantly log in, especially if the browser does not remember the password.





You can email me at iliyazelenkog@gmail.com if you want.

**Comment by shmdesign** [comment]
This is now closed
