### ISSUE TITLE
Implementation in current Laravel Project

### ISSUE THREAD

**Issue by dmartinez777** [iliyaZelenko/laravel5.7-vue-cli3-boilerplate#3]
Hi, quick questions, how do I implement this in to my  current Laravel 5.7 website. Do I just clone it in to my web directory? Or is there a better way?

Currently I have followed what was stated here

https://stackoverflow.com/questions/52362927/laravel-email-verification-5-7-using-rest-api

and everything seems to work, however when I click on the "Verify Email Address" I get transferred to my incorrect login API route (By incorrect I mean /api/login instead of /login). I am aware that this has a lot to do with

```php
$this->middleware('auth');
```
would it be possible to just grab the files needed?

I would really like to use this before I decide to write my own. Any help would be greatly appreciated.

**Comment by 777genius** [comment]
The best way to add this functionality is to follow the instructions in the stackoverflow.  Most likely you have a redirect from the fact that the user is not authenticated.

Why do you have the route "/api/login" instead of "/login" I can only guess. I do not use similar routes in this project. And it is not clear why you are redirected to the REST API, this is strange. 

Maybe you should just comment out this [function](https://github.com/iliyaZelenko/laravel5.7-vue-cli3-boilerplate/blob/master/app/Http/Middleware/Authenticate.php#L17).

Hope this helped.

**Comment by dmartinez777** [comment]
Thank you for the reply. I ended up just writing my own function.
